export const START_WORKING_SUCCESS = 'START_WORKING_SUCCESS';
export const IS_WORKING = 'IS_WORKING';
export const START_WORK = 'START_WORK';
export const END_WORK = 'END_WORK';
export const LOAD_ALL_TIMER = 'LOAD_ALL_TIMER';
export const SAVED_SELECTED_TIMER = 'SAVED_SELECTED_TIMER';


